version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /data/db:/data/db
    networks:
      - node-network
  node_backend:
    depends_on:
      - mongodb
    build: .
    volumes:
      - /data/db
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_PORT=3000
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
